### ISSUE TITLE
Colorbar range on Area plot is not always helpful

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#737] opened 2020-07-02 13:02 UTC
**Describe the bug**
Sometimes the colorbar in an area plot is [-0.1, 0.1]. This occurs for multiple variables (eg. Temperature, Salinity and Water Velocity)

**To Reproduce**
This isn't always reproducible but here is a [link](http://navigator.oceansdata.ca/public/?query=%7B%22area%22%3A%5B%7B%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%2C%22polygons%22%3A%5B%5B%5B58.409385175386745%2C-46.031489372253425%5D%2C%5B44.03495419973615%2C-61.57836675643921%5D%2C%5B41.512232269575435%2C-52.125242948532104%5D%2C%5B50.39217582113662%2C-38.45336914062499%5D%2C%5B58.409385175386745%2C-46.031489372253425%5D%5D%5D%7D%5D%2C%22center%22%3A%5B%22-50.0000%22%2C%2253.0000%22%5D%2C%22dataset%22%3A%22giops_fc_10day_3dps%22%2C%22depth%22%3A0%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22showModal%22%3Atrue%2C%22subquery%22%3A%7B%22bathymetry%22%3Atrue%2C%22colormap_diff%22%3A%22default%22%2C%22contour%22%3A%7B%22colormap%22%3A%22default%22%2C%22hatch%22%3Afalse%2C%22legend%22%3Atrue%2C%22levels%22%3A%22auto%22%2C%22variable%22%3A%22none%22%7D%2C%22convertToUserGrid%22%3Afalse%2C%22currentTab%22%3A1%2C%22dataset_0%22%3A%7B%22dataset%22%3A%22giops_fc_10day_3dps%22%2C%22dataset_attribution%22%3A%22The%20Canadian%20Centre%20for%20Meteorological%20and%20Environmental%20Prediction%22%2C%22dataset_quantum%22%3A%22day%22%2C%22depth%22%3A0%2C%22time%22%3A2225620800%2C%22variable%22%3A%22vosaline%22%2C%22variable_scale%22%3A%2230%2C40%22%7D%2C%22dpi%22%3A144%2C%22leftColormap%22%3A%22default%22%2C%22linearthresh%22%3A200%2C%22output_endtime%22%3A2225620800%2C%22output_format%22%3A%22NETCDF4%22%2C%22output_starttime%22%3A2225620800%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22quiver%22%3A%7B%22colormap%22%3A%22default%22%2C%22magnitude%22%3A%22length%22%2C%22variable%22%3A%22none%22%7D%2C%22rightColormap%22%3A%22default%22%2C%22scale%22%3A%22-5%2C30%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22setDefaultScale%22%3Atrue%2C%22showarea%22%3Atrue%2C%22size%22%3A%2210x7%22%2C%22surfacevariable%22%3A%22none%22%2C%22syncLocalToGlobalState%22%3Afalse%2C%22zip%22%3Afalse%7D%2C%22time%22%3A2225620800%2C%22variable%22%3A%22votemper%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A4%7D) where I've seen this behaviour. This is the GIOPS 10-day Forecast 3D - Polar Stereographic dataset.

It seems to occur when the area plot is partially over land but that's not always true. I'm wondering if there are NaNs in the data that aren't accounted for/removed when calculating the max/min data range.

**Expected behavior**
The colorbar range should be scaled with the max/min of the data.

**Screenshots**
<img width="913" alt="Capture1" src="https://user-images.githubusercontent.com/9750865/86361737-db3e8500-bc4e-11ea-9740-ca0c5616d36b.PNG">
<img width="908" alt="Capture" src="https://user-images.githubusercontent.com/9750865/86361760-df6aa280-bc4e-11ea-9798-bdaeaf23d3d9.PNG">

**Comment by JustinElms** [comment] 2023-09-28 14:13
Closing for now - can't reproduce.

**Closed by JustinElms** 2023-09-28 14:13 UTC
Labels: Bug
