### ISSUE TITLE
Tripolar lines in velocity plot - Arctic view

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#53] opened 2017-08-03 16:54 UTC
[Arctic view tripolar lines](http://navigator.oceansdata.ca/?query=%7B%22center%22%3A%5B%2280.4321%22%2C%2279.5593%22%5D%2C%22zoom%22%3A2%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A32661%22%2C%22time%22%3A114%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22scale%22%3A%220%2C3%22%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22subquery%22%3A%7B%22selected%22%3A1%2C%22scale%22%3A%220%2C3%2Cauto%22%2C%22colormap%22%3A%22default%22%2C%22showarea%22%3Afalse%2C%22surfacevariable%22%3A%22none%22%2C%22linearthresh%22%3A200%2C%22bathymetry%22%3Atrue%2C%22quiver%22%3A%7B%22variable%22%3A%22none%22%2C%22magnitude%22%3A%22length%22%2C%22colormap%22%3A%22default%22%7D%2C%22contour%22%3A%7B%22variable%22%3A%22none%22%2C%22colormap%22%3A%22default%22%2C%22levels%22%3A%22auto%22%2C%22legend%22%3Atrue%2C%22hatch%22%3Afalse%7D%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22size%22%3A%2210x7%22%2C%22dpi%22%3A72%2C%22variable_scale%22%3A%220%2C3%22%2C%22depth%22%3A%220%22%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22area%22%3A%5B%7B%22polygons%22%3A%5B%5B%5B66.854593725666%2C-127.31241594006615%5D%2C%5B67.27130760980332%2C-54.83951460589132%5D%2C%5B67.63068535797869%2C53.47604143072642%5D%2C%5B67.43513534183177%2C129.00978351534692%5D%2C%5B66.854593725666%2C-127.31241594006615%5D%5D%5D%2C%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%7D%5D%7D)

**Comment by Jeffreydaw** [comment] 2017-08-04 19:29
as seen in this screen grab, there are lines are visible in the pole projection.  this seems to be the result of a misinterpretation of the around the pole possibility because of the tripolar projection used in the GIOPS data. 
![selection_023](https://user-images.githubusercontent.com/11149030/28981650-2b146314-792d-11e7-8749-25fa14b138f5.png)

and as can be seen [here](http://navigator.oceansdata.ca/public/?query=%7B%22center%22%3A%5B%22-100.5357%22%2C%2288.8100%22%5D%2C%22zoom%22%3A5%2C%22dataset%22%3A%22giops_day%22%2C%22projection%22%3A%22EPSG%3A32661%22%2C%22time%22%3A513%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22scale%22%3A%5B0%2C3%5D%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22subquery%22%3A%7B%22selected%22%3A1%2C%22scale%22%3A%220%2C3%2Cauto%22%2C%22colormap%22%3A%22default%22%2C%22showarea%22%3Atrue%2C%22surfacevariable%22%3A%22none%22%2C%22linearthresh%22%3A200%2C%22bathymetry%22%3Atrue%2C%22quiver%22%3A%7B%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22magnitude%22%3A%22length%22%2C%22colormap%22%3A%22default%22%7D%2C%22contour%22%3A%7B%22variable%22%3A%22none%22%2C%22colormap%22%3A%22default%22%2C%22levels%22%3A%22auto%22%2C%22legend%22%3Atrue%2C%22hatch%22%3Afalse%7D%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22size%22%3A%2210x7%22%2C%22dpi%22%3A72%2C%22variable_scale%22%3A%5B0%2C3%5D%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22area%22%3A%5B%7B%22polygons%22%3A%5B%5B%5B87.39067509353906%2C-135.0780064807113%5D%2C%5B87.71338859661515%2C-35.119495501760206%5D%2C%5B87.22075725717644%2C55.03332394728415%5D%2C%5B87.33367152949945%2C145.3859338198518%5D%2C%5B87.39067509353906%2C-135.0780064807113%5D%5D%5D%2C%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%7D%5D%7D) the arrows do not line up as expeced around the lines.
![selection_024](https://user-images.githubusercontent.com/11149030/28983864-2983adf8-7936-11e7-8464-e9168dd34a70.png)

**Comment by Jeffreydaw** [comment] 2017-09-01 15:33
The tripolar grid dose does not come into effect till 40deg north so the problem is probably only above that. This is backed up by the fact that the Labrador current and the currents by Japan both seem to be pointing the correct directions

**Comment by Jeffreydaw** [comment] 2017-09-05 17:47
![selection_032](https://user-images.githubusercontent.com/11149030/30074752-33c253ac-924d-11e7-8a5d-6264a55c204e.png)

[above Russa](http://navigator.oceansdata.ca/?query=%7B%22subquery%22%3A%7B%22selected%22%3A1%2C%22scale%22%3A%22-0.2811656594276428%2C0.11322778463363647%2Cauto%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22leftColormap%22%3A%22default%22%2C%22rightColormap%22%3A%22default%22%2C%22diffColormap%22%3A%22default%22%2C%22showarea%22%3Atrue%2C%22surfacevariable%22%3A%22none%22%2C%22linearthresh%22%3A200%2C%22bathymetry%22%3Atrue%2C%22quiver%22%3A%7B%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22magnitude%22%3A%22length%22%2C%22colormap%22%3A%22default%22%7D%2C%22contour%22%3A%7B%22variable%22%3A%22none%22%2C%22colormap%22%3A%22default%22%2C%22levels%22%3A%22auto%22%2C%22legend%22%3Atrue%2C%22hatch%22%3Afalse%7D%2C%22variable%22%3A%5B%22vomecrty%22%5D%2C%22size%22%3A%2210x7%22%2C%22dpi%22%3A144%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22area%22%3A%5B%7B%22polygons%22%3A%5B%5B%5B82.91623498977847%2C-294.952759199955%5D%2C%5B81.54098871241459%2C-294.18317729557117%5D%2C%5B81.65344686397677%2C-281.2926803971423%5D%2C%5B83.2180896387807%2C-281.1002849210464%5D%2C%5B82.91623498977847%2C-294.952759199955%5D%5D%5D%2C%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%7D%5D%2C%22center%22%3A%5B%22-268.5194%22%2C%2266.7260%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22zoom%22%3A2.8697063146177397%2C%22dataset%22%3A%22giops_day%22%2C%22variable%22%3A%22vomecrty%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A484%7D)

**Comment by nsoontie** [comment] 2018-02-02 13:55
The tripolar lines are an artifact of the rotation of the GIOPS grid lines. Above about 40 deg N, the x grid lines are no longer aligned east/west.

![giops_grid_angle](https://user-images.githubusercontent.com/9750865/35736574-1bf0028e-0803-11e8-8c31-76e55bf0d0ae.png)
![giops_grid_angle_polar](https://user-images.githubusercontent.com/9750865/35736583-20472254-0803-11e8-8b15-c6aae7ce389c.png)

We can correct this issue by calculating the angle between the xgrid lines and east, and then rotating the velocity fields upon loading. The angle can be computed once for each grid and saved in a netcdf file listed in the model's config file.

**Comment by Jeffreydaw** [comment] 2018-02-28 14:43
This problem can also be seen in GLORYS but the lines are a little different. 

![tri_polar_glorys](https://user-images.githubusercontent.com/11149030/36793379-d7903a08-1c77-11e8-9d9a-66b061ed7ea9.png)

[navigator link](http://navigator.oceansdata.ca/public/?query=%7B%22basemap%22%3A%22topo%22%2C%22center%22%3A%5B%2238.6081%22%2C%2287.7129%22%5D%2C%22dataset%22%3A%22glorys_climatology%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22depth%22%3A0%2C%22time%22%3A720%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%7D%2C%22dataset_compare%22%3Afalse%2C%22depth%22%3A0%2C%22projection%22%3A%22EPSG%3A32661%22%2C%22time%22%3A11%2C%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22vectorid%22%3Anull%2C%22vectortype%22%3Anull%2C%22zoom%22%3A3%7D)

see page 40 of [PRODUCT USER MANUAL](http://cmems-resources.cls.fr/documents/PUM/CMEMS-GLO-PUM-001-004-009-010-011-017.pdf) to see the used grid (I belive that is the correct product manual)

**Comment by nsoontie** [comment] 2018-03-07 18:38
grid_angle.nc files created for riops (usergrid), giops, salishsea, gulf and glorys

Note: Glorys needs to be interpolated to A-grid

Next step: Write config files and code for handling rotation.

**Comment by nsoontie** [comment] 2018-04-04 18:37
There are still minor errors for velocities at the northfold on ORCA grids. These errors are small, ~1% and can be seen in the test_giops_east, north, north_east datasets.

The errors are a result of the rotation. I will investigate further.

**Comment by Jeffreydaw** [comment] 2018-07-19 17:15
The fix of pre-rotating the files seems to have caused problems with the THREDDS server. the change was reverted and we need to explore other options

**Comment by htmlboss** [comment] 2019-05-15 15:45
This error is fixed with Geoff's calculation layer (#378)

**Closed by htmlboss** 2019-05-15 15:45 UTC
Labels: Priority: Medium
