### ISSUE TITLE
Failing Tiles

### ISSUE THREAD

**Issue by halehkh65** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#375] opened 2019-02-21 17:37 UTC
when you disable max zoom, and then try zooming in really far,  the tiles will start failing

**Comment by jmunroe** [comment] 2019-02-21 17:39
So the current behaviour is to throw an exception when the tile cannot be drawn?  I suggest two improvements:

1. Printing out a log message indicating that a title could not be fully created.
2. Return a 'dummy' title instead so the upper layers of the stack have something to process.

**Comment by NoahGallant-MUN** [comment] 2019-02-21 17:40
Assuming this has to do with the data tiles, the cause appears to be the tile masking which relies on the topography files. The topography files only have 8 zoom levels so it fails to open the file resulting in an error.
The best solution would be probably be to find an alternate way of doing the masking, such as using a vector file like james p is doing

**Comment by NoahGallant-MUN** [comment] 2019-02-21 17:43
Another idea as a temporary solution could be to return the closest zoom level after exceeding the max topographhy file. that way you would still see data it would just get less and less nice looking.

**Comment by jmunroe** [comment] 2019-02-21 17:48
Right. I think @jamesprayner is working on a more general solution.  In the meantime, perhaps we could just fail gracefully if the topography file does not exist at that zoom level?  

What about using the mask for the highest zoom that does exist and projecting that onto the current zoom level? As in, creating the mask for the highest zoom available, and the increase the resolution of the mask for the required zoom level.

Say zoom level 8 gives you

```
1 0 0 0
1 1 0 0 
1 1 0 0
1 1 1 1 
```

then we may be able to assume a mask like

```
1 1 0 0 0 0 0 0
1 1 0 0 0 0 0 0
1 1 1 1 0 0 0 0
1 1 1 1 0 0 0 0
1 1 1 1 0 0 0 0
1 1 1 1 0 0 0 0
1 1 1 1 1 1 1 1
1 1 1 1 1 1 1 1
```

and cropping the masking array appropriately.

**Comment by NoahGallant-MUN** [comment] 2019-02-21 17:58
I like the idea of trying to use the last mask with the new data. Do you think it's worth waiting for a better solution? or worth trying to implement that.
This problem doesn't exist on the public server because we have the max zoom set to 8, so it would only be required when rolling out james p's bathymetry and topography vector method.

**Comment by jmunroe** [comment] 2019-02-21 18:08
I think it fine to stub it out now. If we did something like:

if bathemetry_vector_feature is on:
  return @jamesprayner solution 
else if If topography zoom level exists:
  return current solution
else (topography zoom level does not exist):
  use MAX_ZOOM level  (or whatever the global variable is called, value of 8) to infer 
  correct mask
  return approximately masked tile 

Feature flags are a nice way of setting up production code for when we 'eventually' have new items to roll out.  We probably already have a config.json or something for when we deploy the application, right?

**Comment by jmunroe** [comment] 2019-02-21 18:22
@halehkh65  asked me: "If James create a vector Bathymetry, then I should create a vector topography?"

Sorry, I meant when @jamesprayner has both the vector bathymetry and vector topography feature worked out, we would use that.  Until then, I think @halehkh65 should try and work using the highest zoom level available for masking.

**Comment by halehkh65** [comment] 2019-02-21 18:28
ok, thank you James, I'll try to masking based on highest zoom level available.

**Comment by jamesprayner** [comment] 2019-02-21 18:48
It's important to have legacy features available to those who prefer how the navigator worked before we made changes if its not too much hassle. I don't think its too much effort to stop the tile method from throwing errors, that way you can choose what topography or bathymetry display method you'd want without errors.

Using the highest zoom level tiles like @NoahGallant-MUN and @jmunroe are saying seems like a reasonable solution to me.

**Comment by NoahGallant-MUN** [comment] 2019-02-21 19:02
I think keeping the legacy features in the API is fine, but I'm not sure that having multiple different ways of rendering the map in the browser is useful.

**Comment by halehkh65** [comment] 2019-02-21 19:12
which data masking technique are we using in the application?

**Comment by NoahGallant-MUN** [comment] 2019-02-21 19:21
we currently load the topography file, and then replace every value in the data array, whose depth is less than the height of the topography files data at the same location with a mask.

**Comment by htmlboss** [comment] 2019-05-22 11:44
It might be helpful to visualise the error by attaching a screenshot.

**Comment by jamesprayner** [comment] 2019-05-22 14:57
There's no way for the user to change the max zoom level. I'm closing this issue since, if a higher-than-supported zoom level is reached, the navigator isn't properly deployed.

**Closed by jamesprayner** 2019-05-22 14:57 UTC
Labels: Priority: Low, Python, enhancement, needs-more-info
