### ISSUE TITLE
Data issues with 10d forecast 

### ISSUE THREAD

**Issue by VanessaSutton-Pande** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#68] opened 2017-08-10 13:28 UTC
Missing data on THREADDS as compared to the datamart for GIOPS 10d forecast. The missing data is not consistent across variables; a. skipping days Aug. 10 -15, 16 erroneous, 17 missing, 18th erroneous, b. on Aug. 9 there were 9 days of data (Aug. 10-18) and on Aug. 10 there were 10 days of data (Aug. 10-19).

**Comment by clydeclements** [comment] 2017-08-10 13:54
When Vanessa first reported a problem to me yesterday, I confirmed that data was missing on the production server. Checking again about an hour later, I found the data was there. One possibility: maybe a cron job to pull down new data was in progress at the time that the issue was first noted, with THREDDS refreshing its view of files during that cron job and leading to a view of an incomplete data set?

Presently, I have no idea if these data-pull jobs take 30 seconds, 5 minutes or 2 hours to complete. So to get a better handle on things, I have modified three of the scripts called as cron jobs: `sync_gem.sh`, `sync_giops_forecast.sh`, and `sync_riops.sh`. The scripts were modified to print log messages of progress via the system `logger` command; such messages are captured by the `rsyslod` process. Next I created a configuration file:
```
  /etc/rsyslog.d/10-ocean-navigator-scripts.conf
```
which instructs `rsyslod` to direct these messages to the log file:
```
  /var/log/oceannavigator/ocean-navigator-scripts.log
```
rather than cluttering up the `/var/log/syslog` file. Lastly, I restarted `rsyslod`:
```
  sudo service rsyslog restart
```
Hopefully, the log messages will help in diagnosing any future problems.

**Comment by clydeclements** [comment] 2017-08-18 18:33
Now that the modified scripts have been running for a few days and logging information, I analyzed the log file for details about the cron jobs.

The `sync_riops.sh` script runs 8 times per day with the first run at midnight and then every 3 hours thereafter. (Those details could have been determined from the actual `crontab` file.) Half of the runs (at midnight, 6am, 12pm and 6pm) take only seconds to run (about 10 seconds). This is likely because there is no new data at those times and thus nothing to transfer. The other half of the runs (at 3am, 9am, 3pm and 9pm) take about 10 or 11 minutes to run.

The `sync_gem.sh` script runs 8 times per day with the first run at 12:30am and then every 3 hours thereafter. All of the runs take mere seconds because the data transferred is quite small (on the order of kilobytes).

The `sync_giops_forecast.sh` script runs 4 times per day with the first run at 12:45am and then every 6 hours thereafter. The job at 12:45am takes mere seconds to run, presumably because there is no new data at that time. The other jobs take minutes to complete, on the order of 10-15 minutes, but even longer in some cases. The 6:45pm job on August 14, for example, took 35 minutes to finish.

At present, the GIOPS forecast cron job downloads the data to a directory watched by the THREDDS data server. It is therefore possible that the data issues observed with the GIOPS 10 day forecast may be a race condition between the cron jobs and the THREDDS data server. To elaborate, the THREDDS data server may refresh its list of available files while the cron job to pull down GIOPS forecast data is still in progress. This has not been confirmed though.

One possible fix would be to modify the cron job to download data to a temporary directory and, upon completion, move the data to the THREDDS data directory.

**Comment by Jeffreydaw** [comment] 2017-09-06 19:49
looking deeper into this it seems that the files do in fact get downloaded before the old ones are removed (as it should be).  And the aggregated.ncml file that threads get is also updated. the best theory at the moment is that threads is using the cached version of the aggregated.ncml file it has stored in '/data/thredds/cache/agg/data/GIOPS/forecast/aggregated.ncml#null' and that it is only updating the cached threads file every hour. This would mean that it is pointing to files that don't exist. 

This may not be the case as it was indicated that some of the files could be accessed.

**Comment by Jeffreydaw** [comment] 2017-10-25 13:37
I'm removing the urgent tag and moving this to the icebox because it is no longer causing problems for VanessaSutton-Pande. Their scripts are running at a different time now which no longer overlaps with the time our data is updating.
This does not mean we should not find out what is causing this problem.

**Closed** 2023-09-27 17:56 UTC
Labels: Bug, Priority: Low
