### ISSUE TITLE
Direction of velocity vectors in different projections don't match

### ISSUE THREAD

**Issue by nsoontie** [DFO-Ocean-Navigator/Ocean-Data-Map-Project#188] opened 2018-01-26 15:44 UTC
This issue is not related to the tripolar grid because I am plotting from GIOPS forecast.

For a vector plot generated from the Arctic projection mode
[link](http://navigator.oceansdata.ca/public/?query=%7B%22subquery%22%3A%7B%22selected%22%3A1%2C%22scale%22%3A%22-0.3%2C0.3%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22leftColormap%22%3A%22default%22%2C%22rightColormap%22%3A%22default%22%2C%22diffColormap%22%3A%22default%22%2C%22showarea%22%3Atrue%2C%22surfacevariable%22%3A%22none%22%2C%22linearthresh%22%3A200%2C%22bathymetry%22%3Atrue%2C%22quiver%22%3A%7B%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22magnitude%22%3A%22length%22%2C%22colormap%22%3A%22default%22%7D%2C%22contour%22%3A%7B%22variable%22%3A%22none%22%2C%22colormap%22%3A%22default%22%2C%22levels%22%3A%22auto%22%2C%22legend%22%3Atrue%2C%22hatch%22%3Afalse%7D%2C%22variable%22%3A%5Bnull%5D%2C%22size%22%3A%2210x7%22%2C%22dpi%22%3A144%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22output_starttime%22%3A0%2C%22output_endtime%22%3A1%2C%22output_format%22%3A%22NETCDF3_CLASSIC%22%2C%22zip%22%3Afalse%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22area%22%3A%5B%7B%22polygons%22%3A%5B%5B%5B77.00013546354198%2C16.080912473975385%5D%2C%5B66.07041503892299%2C58.57447120048371%5D%2C%5B69.55292724185699%2C103.35862742441087%5D%2C%5B83.45926177742525%2C145.30638469764173%5D%2C%5B77.00013546354198%2C16.080912473975385%5D%5D%5D%2C%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%7D%5D%2C%22center%22%3A%5B%220.0000%22%2C%2290.0000%22%5D%2C%22projection%22%3A%22EPSG%3A32661%22%2C%22basemap%22%3A%22topo%22%2C%22dataset_compare%22%3Afalse%2C%22zoom%22%3A2%2C%22dataset%22%3A%22giops_forecast%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22depth%22%3A0%2C%22time%22%3A689%7D%2C%22variable%22%3A%22vomecrty%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A0%7D)

For a vector plot generated from the Global projection mode
[link](http://navigator.oceansdata.ca/public/?query=%7B%22subquery%22%3A%7B%22selected%22%3A1%2C%22scale%22%3A%22-0.3%2C0.3%22%2C%22scale_1%22%3A%22-5%2C30%2Cauto%22%2C%22scale_diff%22%3A%22-10%2C10%2Cauto%22%2C%22leftColormap%22%3A%22default%22%2C%22rightColormap%22%3A%22default%22%2C%22diffColormap%22%3A%22default%22%2C%22showarea%22%3Atrue%2C%22surfacevariable%22%3A%22none%22%2C%22linearthresh%22%3A200%2C%22bathymetry%22%3Atrue%2C%22quiver%22%3A%7B%22variable%22%3A%22vozocrtx%2Cvomecrty%22%2C%22magnitude%22%3A%22length%22%2C%22colormap%22%3A%22default%22%7D%2C%22contour%22%3A%7B%22variable%22%3A%22none%22%2C%22colormap%22%3A%22default%22%2C%22levels%22%3A%22auto%22%2C%22legend%22%3Atrue%2C%22hatch%22%3Afalse%7D%2C%22variable%22%3A%5Bnull%5D%2C%22size%22%3A%2210x7%22%2C%22dpi%22%3A144%2C%22output_timerange%22%3Afalse%2C%22output_variables%22%3A%22%22%2C%22output_starttime%22%3A0%2C%22output_endtime%22%3A1%2C%22output_format%22%3A%22NETCDF3_CLASSIC%22%2C%22zip%22%3Afalse%7D%2C%22showModal%22%3Atrue%2C%22modal%22%3A%22area%22%2C%22names%22%3A%5B%5D%2C%22area%22%3A%5B%7B%22polygons%22%3A%5B%5B%5B79.7454886493513%2C12.473965544028351%5D%2C%5B84.71994580315419%2C102.82552804402835%5D%2C%5B71.7386103430238%2C118.82162179402835%5D%2C%5B56.835317177488236%2C32.688809294028346%5D%2C%5B79.7454886493513%2C12.473965544028351%5D%5D%5D%2C%22innerrings%22%3A%5B%5D%2C%22name%22%3A%22%22%7D%5D%2C%22center%22%3A%5B%2296.9984%22%2C%2273.1177%22%5D%2C%22projection%22%3A%22EPSG%3A3857%22%2C%22basemap%22%3A%22topo%22%2C%22dataset_compare%22%3Afalse%2C%22zoom%22%3A3%2C%22dataset%22%3A%22giops_forecast%22%2C%22dataset_1%22%3A%7B%22dataset%22%3A%22giops_day%22%2C%22dataset_attribution%22%3A%22GIOPS%20Daily%20Values%20from%20CONCEPTS%22%2C%22dataset_quantum%22%3A%22day%22%2C%22variable%22%3A%22votemper%22%2C%22variable_scale%22%3A%5B-5%2C30%5D%2C%22depth%22%3A0%2C%22time%22%3A688%7D%2C%22variable%22%3A%22vomecrty%22%2C%22depth%22%3A0%2C%22vectortype%22%3Anull%2C%22vectorid%22%3Anull%2C%22time%22%3A0%7D)

The vectors in each aren't pointed in the same direction. For example, around 60 E, 70 N:
Global plot shows vectors pointing along the island
Arctic plot shows vectors pointing across the island

The issue could be related to interpolating the velocity vectors or plotting vectors in basemap (eg. is rotate_vector being used correctly??).

**Comment by Jeffreydaw** [comment] 2018-01-26 17:31
I had not thought to check this. It works with a theory I have had about the problem, I have suspected for a while that this is caused by matplotlib using x and y as the image x,y as oppose to the lat, long x,y . This may, in fact, be the case. (or not, it's still not proven)

**Comment by clydeclements** [comment] 2018-01-26 20:28
The `rotate_vector` from basemap is not being used anywhere in the code. It's still possible that there is some custom code to handle the transformation of the velocity vectors. However, I have yet to find any such code.

**Comment by nsoontie** [comment] 2018-03-07 18:50
We need to switch to using rotate_vector instead of latlon=True in basemap quiver. We also need to  ensure that velocities given to rotate_vector are eastward and northward (to be resolved in another issue: #53 )

**Comment by nsoontie** [comment] 2018-03-09 19:54
Pushed branch nancy_quiver. Issue is corrected with a call to rotate_vector and was tested on east/north test_datasets.

**Comment by nsoontie** [comment] 2018-03-26 16:09
b321fb11c25b28198ee30cf627a6ffd666429615

**Comment by nsoontie** [comment] 2018-08-02 10:57
This is labelled as Done so no additional changes are needed (unless something changed with python 3 which I haven't checked)

**Comment by Jeffreydaw** [comment] 2018-08-02 20:02
@nsoontie in that case I'll close it as that commit was merged into master.

**Closed by Jeffreydaw** 2018-08-02 20:02 UTC
Labels: Python, discussion wanted, severe bug
